name: CI
on:
  push:
    branches:
      - "release/**"

jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image for x86_64 with BIOS mode
        run: |
          sudo ./alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 2G \
              --partition \
              --repositories-file example/repositories \
              --packages "$(cat example/packages)" \
              --script-chroot \
              custom_alpine-x86_64-bios-cloudinit.qcow2 -- ./example/configure.sh

      - name: Store build timestamp
        run: echo "BUILD_ID=action/$(date +'%Y%m%dT%H%M%SZ')" >> $GITHUB_ENV

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ env.BUILD_ID }}
          tag_exists_error: false
          message: "Release ${{ env.BUILD_ID }}"

      - name: Add image to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.BUILD_ID }}
          files: custom_alpine-x86_64-bios-cloudinit.qcow2
