name: CI
on:
  push:
    branches:
      - "release/**"

jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image for x86_64 with BIOS mode and GPT
        run: |
          sudo ./alpine-make-vm-image \
              --image-format raw \
              --image-size 2G \
              --partition \
              --repositories-file example/repositories \
              --packages "$(cat example/packages)" \
              --script-chroot \
              alpine-bios-part-$(date +%Y-%m-%d).raw -- ./example/configure.sh

      - name: Add image to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            alpine-bios-part-$(date +%Y-%m-%d).raw
